meta_product_name: "Izireach"
meta_title: "Izireach - Marketing tool that will change your life"
meta_description: "Helping brands & influencers find the perfect match !"
meta_image: "logo_izireach.png" # should exist in `app/assets/images/`
twitter_account: "@julienrdg"